//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music_Player.Models
{
    using Music_Player.Utilities;
    using System;
    using System.Collections.Generic;
    
    public partial class Song :ViewModelBase
    {
        private int songID;
        private string artist;
        private string title;
        private string path;
        private TimeSpan? duration;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Song()
        {
            this.Playlists = new HashSet<Playlist>();
        }

        public int SongID { get => songID; set => songID = value; }
        public string Artist { get => artist; set => artist = value; }
        public string Title { get => title; set { title = value; OnPropertyChanged(nameof(Title)); } 
        }
        public string Path { get => path; 
            set { 
                path = value;
                OnPropertyChanged(nameof(Path));
            }
        }
        public Nullable<System.TimeSpan> Duration { get => duration; set { duration = value; OnPropertyChanged(nameof(Duration)); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Playlist> Playlists { get; set; }
    }
}
